import Deck from '@/components/Deck';

const sampleCards = [
  {
    id: '1',
    question: 'What is Next.js?',
    answer: 'Next.js is a React framework that enables functionalities such as server-side rendering and generating static websites for React based web applications.'
  },
  {
    id: '2',
    question: 'What is Server-Side Rendering (SSR)?',
    answer: 'SSR is the ability of an application to contribute by displaying the web-page on the server instead of rendering it in the browser. Server-side sends a fully rendered page to the client.'
  },
  {
    id: '3',
    question: 'How do you create a new page in Next.js App Router?',
    answer: 'By creating a page.tsx file inside a folder within the app directory. The folder path becomes the route path.'
  },
  {
    id: '4',
    question: 'What is the purpose of "use client"?',
    answer: 'It marks a component as a Client Component, allowing it to use React hooks and event listeners like onClick.'
  },
  {
    id: '5',
    question: 'What is Hydra?',
    answer: 'In Greek mythology, a serpent-like monster. In web dev, Hydration is the process of attaching event listeners to the DOM nodes generated by SSR.'
  }
];

export default function Home() {
  return (
    <main style={{
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '100vh',
      padding: '2rem',
    }}>
      <h1 className="title-gradient" style={{
        fontSize: '4rem',
        fontWeight: '800',
        marginBottom: '1rem',
        textAlign: 'center',
        textTransform: 'uppercase',
        letterSpacing: '5px'
      }}>
        FlashCards
      </h1>
      <p style={{
        color: 'var(--text-secondary)',
        marginBottom: '3rem',
        fontSize: '1.2rem'
      }}>
        Master your knowledge one card at a time.
      </p>

      <Deck cards={sampleCards} />
    </main>
  );
}
